### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by Gamecrafter**
Fixes some typos(not all), fixes comparison operators. Learn more about comparison operators here: http://php.net/manual/en/language.operators.comparison.php and assignment operators: http://php.net/manual/en/language.operators.assignment.php

### CODE REVIEW

**Comment by xxFlare** [comment]
I already know about operators, this is just a direct result of switching from coding languages and copy and paste.

**Comment by xxFlare** [comment]
Also... If you checked commits I made days ago... I'm using md5(), this must be an old branch.

**Comment by Gamecrafter** [comment]
Copy and paste? :astonished: No, you still have "xauth" being used in hash(), it isn't registered. Unless you are planning to create your own algorithm and register it, you shouldn't be using that algorithm(xauth).

**Comment by xxFlare** [comment]
Ah ok, Forgot I left that there.

I'll push some updates after I finish more FlareFlash work.

**Comment by Gamecrafter** [comment]
Ok. ;)

**Comment by xxFlare** [comment]
Merged.

**Comment by xxFlare** [comment]
Merged.

**Pull request merged**
